
Promise.reject('failed').catch(console.log('Ooops something went wrong'))


const urls = [
  'https://jsonplaceholder.typicode.com/users',
  'https://jsonplaceholder.typicode.com/posts',
  'https://jsonplaceholder.typicode.com/albums',
]



const promise1 = Promise.resolve(console.log('success'));

Promise.all(urls.map(url => {
   return fetch(url).then(resp => resp.json())
})).then(results => {
  console.log('1' ,results[0])
  console.log(results[1])
  console.log(results[2])

}).catch(error => console.log('uhoh',error))

const getData = async function() {
  try{
  const [users, posts, albums] = await Promise.all(urls.map(url => {
    return fetch(url).then(resp => resp.json())}))
    console.log(users)
    console.log(posts)
    console.log(albums)
  }catch(error){
    console.log('nooooo',error)
  }
}
getData();